name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  swiftpm:
    name: SwiftPM
    runs-on: macos-15

    steps:
      - name: Checkout
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - name: Swift version
        run: swift --version

      - name: Build
        run: swift build

      - name: Test
        run: swift test
